name: Django CI

on:
  push:
    branches: [ main ]
    #paths:
    #  - "src/cognigy/**"
  pull_request:
    branches: [ main ]
    #paths:
    #  - "src/cognigy/**"

jobs:
  build:
    name: Build Source Code
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: src/cognigy
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: src/cognigy
      run: |
        python manage.py test

  image:
    needs: build
    name: Create and test image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and run Image
      run: docker-compose up -d
    - name: Show runnig images
      run: docker ps -a
    